version: 2
jobs:
  build:
    working_directory: &working_directory
      go/src/github.com/vic3r/smart-cities-back
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run:
          name: Install dep
          command: go get -u github.com/golang/dep/cmd/dep
      - run:
          name: Install dependencies
          command: dep ensure
      - run:
          name: Install golang-lint
          command: go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
  lint:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run:
          name: Check style
          command: golangci-lint run

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint:
          requires:
            - build
          filters:
            branches:
              only: development